### ISSUE TITLE
Please don't use pacman for CI

### ISSUE THREAD

**Issue by WinterMute** [sergiou87/open-supaplex#2]
Using pacman to install the toolchains for CI hits our servers for every commit and makes it look like there are many, many more users on linux than there really are.

We provide docker images for CI purposes, it would be awesome if you used those instead. See https://hub.docker.com/u/devkitpro

**Comment by sergiou87** [comment]
Ohh I didn’t know about that, sorry! I’ll take a look and make the change ASAP

**Comment by sergiou87** [comment]
I think this should be fine now :D

**Comment by WinterMute** [comment]
Nice one. Much appreciated. Thanks.
