### ISSUE TITLE
change the banner please.

### ISSUE THREAD

**Issue by BobRocks20** [sergiou87/open-supaplex#21]
no seriously. I just installed the .cia on my 3ds and the banner is creeping me out. as if having that thing in the icon wasn't enough...
![2021-05-28_15-58-26 914_top](https://user-images.githubusercontent.com/72172937/120049177-07cd5f00-bfce-11eb-9a87-ca0ba11a858b.png)

**Comment by sergiou87** [comment]
You're gonna be surprised when you open the game and see that's the main character of the game 😝 

Seriously, I'm open to suggestions. But without better ideas, I won't change the banner, sorry 😅

**Comment by BobRocks20** [comment]
maybe use the title screen?

**Comment by MrHuu** [comment]
I'd like to make a few suggestions:

![supaplex_banner](https://user-images.githubusercontent.com/561623/133889834-461240ca-d58f-4597-b900-85d15d91f3da.png)

![supaplex_banner_alt](https://user-images.githubusercontent.com/561623/133889833-65ad00e8-ed41-4536-8d3a-d1da46fe55f6.png)

**Comment by sergiou87** [comment]
Thanks for the suggestions, @MrHuu , but I'd rather keep the current image 😅
