### ISSUE TITLE
Version 7.2

### ISSUE THREAD

**Issue by serdeliuk** [sergiou87/open-supaplex#25]
Hello,

I have ported this to my Vu Solo4K satellite Linux ARM CPU receiver and works pretty well, thanks for making this available.

I am almost ready to publish a bitbake recipe that contains my Enigma2 plugin and this wonderful game.
My bitbake recipe will use your source code directly from github and apply some patches to make the code run on OpenEmbedded env plus add infrared remote control and keys, which are by the way missing in any SDL version.

I wonder if you can publish the 7.2, I want to use in my recipe a stable version instead of master :)

Many thanks,

Marc

**Comment by sergiou87** [comment]
Hey! I want to publish 7.2 but I can't find the time, since I'd like to test the new build in all the platforms I initially released it for (Wii, Wii U, 3DS, PS3, PSP, PS Vita, macOS and Windows...). I also have some PRs to check but yeah, no time lately 😢 I'll do my best to get something in the upcoming weeks 🤞

**Comment by serdeliuk** [comment]
Thanks for the update, i will use the latest commit then, currently i am still testing the latest version, so far i was able to see that resources folder do not contain all wav files, there are some xm files that are not playable, i didn't dig to see if the game is capable to play them, but i noticed that there is no music.

**Comment by serdeliuk** [comment]
I have used flac instead of wav on those huge music files, still big but not huge :) i am unable to make mikmod to work on my box unfortunately...

**Comment by sergiou87** [comment]
Oh, if mikmod doesn't work, I think SDL_mixer also supports modplug. Although I'm surprised mikmod doesn't work, I never had issues with it so far 😳

**Comment by serdeliuk** [comment]
modplug does not work as well unfortunately, i didn't dig too much to see why....

**Comment by DarthGandalf** [comment]
Any plans for new release? :)

**Comment by sergiou87** [comment]
I've been planning a new release for a long time, but I'd like to test as many ports as I can before doing so, which is a pain 😂 I'll try to make some time when #42 and #43 are merged, along with some changes in the PS2 port mentioned by @fjtrujy in #37 and a CI job for PS2!
