### ISSUE TITLE
THANK YOU

### ISSUE THREAD

**Issue by alexeyqu** [sergiou87/open-supaplex#34]
This was effectively my first game -- back in 2002-ish, on a Win95 PC of my friend.
We never got past level 20 or so back then... because we were 8 years old.
Since then, from time to time I recalled this game and tried to play -- Dosbox emulators that could crash irreversibly once you have completed 40 levels, endless remakes that lacked the most important thing (THAT feeling, but also Murphy's facial expressions etc).
All of that was more disturbing than fun...until I found this gem.

Wow, bravo. Was that your quarantine pet project? :)

P.S. You owe me 50 hours of my life, which I traded for pure joy and nostalgia -- a great deal, by the way!

**Comment by alexeyqu** [comment]
Oh, I found your story on Twitter. Indeed a quarantine pet project.

Thanks again, so much awesome work.

**Comment by sergiou87** [comment]
LOL! Thank you for your kind words!! Your story resembles mine, I just started playing it a few years earlier (in 1995 with my first 486 with Windows 3.11!), and then many years later I was looking for the very same game on my PSP, but DOSBox didn't provide the best experience. And again, many years later… COVID pushed me to work on this project! 😂 

I'm very happy you're having fun with this very awesome game through my humble work in this project 🙏  And I hope it enables you and more people to keep enjoying it for many more years! 😄 

PS: Even though this is the best issue I ever had in my repos, I'll close it to reduce noise. Thank you again for this, it really made my day 🙇‍♂️ ❤️
