### ISSUE TITLE
"roland" theme was another

### ISSUE THREAD

**Issue by U-ENERGY** [sergiou87/open-supaplex#36]
I just have compiled the game on my linux machine, and find out that "roland" music theme don't the same, as in original DOS supaplex. I really loved play with Roland theme, Why did you change that?

**Comment by sergiou87** [comment]
The "Roland" music can't be played with 100% accuracy without an MT-32 or SC-55, but the version included should be accurate enough: it's a mod file with (I think, @mills32 can confirm) the SC-55 soundfont. In any case, this is an open source project, so feel free to contribute with a better and more accurate version of the Roland theme 😄
