### ISSUE TITLE
Switch version keyboard does not work on Applet mode

### ISSUE THREAD

**Issue by rjimenezda** [sergiou87/open-supaplex#4]
The virtual keyboard does not show up if you start the game from an "Applet mode" hbmenu.

I think this is an intended limitation, but it does make it impossible to create a new player, maybe it should fall back to an auto-generated name?

**Comment by sergiou87** [comment]
IIRC the game didn't even work in Applet mode, it just crashed, but I'll take a look and see what I can do 😅

**Comment by rjimenezda** [comment]
As far as I could tell demos, sound and the menu overall worked fine.

I got the repo building locally, so I can take a look as well. My only issue is that sending it over to the switch with nxlink crashes. Maybe it doesn't find the app resources, because netloader puts it on the `/switch` folder directly 🤔

And Btw, thanks a lot for the work, it's one of my childhood games as well 😄😄

**Comment by rjimenezda** [comment]
Oh, there's a --p option on nxlink, my bad :facepalm: 

I have a fix, I'll open a PR :smile:

**Comment by sergiou87** [comment]
Thank you!! FYI I also added a `run` task to the Switch `Makefile` (https://github.com/sergiou87/open-supaplex/blob/master/switch/Makefile#L188), so you can just `make run` from the `switch` folder instead.
