### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by DarthGandalf** [sergiou87/open-supaplex#6]
It works (and I even finished the first level, yay) if I delete part of `supaplex.c` in the `if (supportsVirtualKeyboard())` branch. Without that deletion, the error message is: `supaplex.c:(.text+0xa09e): undefined reference to 'inputVirtualKeyboardText'`

**Comment by sergiou87** [comment]
Yeah, but that's the wrong way to fix it. The right way is adding `src/null/virtualKeyboard.c` to the `Makefile`. `supaplex.c` _shouldn't_ change with each platform.

Are you using the `Makefile` in the repo? Sorry, that was an attempt to run the tests on Linux and left it outdated 😓

**Comment by DarthGandalf** [comment]
Yes, I used `cd linux; make`, then carefully copied files around.

What's difference between real and virtual keyboard? Real one works, so execution doesn't even reach the virtual one.

**Comment by sergiou87** [comment]
The real keyboard is a physical hardware keyboard, the virtual keyboard is the software keyboard for platforms without a physical one: https://twitter.com/sergiou87/status/1257801517987500033
